# This workflow determines the status of web API used by argopy, every 3 minutes

name: api-status

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/3 * * * *'
  push:
    branches: [ master ]

jobs:
  api-check:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout argopy repository
      uses: actions/checkout@v2
      with:
        ref: 'api-status'
#      env:
#        GIT_TRACE: 1
#        GIT_CURL_VERBOSE: 1

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    - name: Install argopy
      run: |
        python -m pip install --upgrade pip
        pwd
        ls -l
        pip install -r requirements.txt
        pip install distributed aiohttp
        pip install argopy

    - name: Check and save API status
      run: |
        python -c "import argopy; argopy.utilities.save_api_status()"
        ls -rtl argopy/assets
